// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhO7-Nz65Cx7NFt-tleuqrCvj7g4PpOQ',
    appId: '1:929386302424:web:1f621c309d375843fb00ad',
    messagingSenderId: '929386302424',
    projectId: 'challenge-app-d20ba',
    authDomain: 'challenge-app-d20ba.firebaseapp.com',
    storageBucket: 'challenge-app-d20ba.firebasestorage.app',
    measurementId: 'G-X2E5EP2QLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZEM9ZUOxW8DCVzqmvSHqctnjkrUt2MO0',
    appId: '1:929386302424:android:cb1945ac0c16b808fb00ad',
    messagingSenderId: '929386302424',
    projectId: 'challenge-app-d20ba',
    storageBucket: 'challenge-app-d20ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlEk21zTh9HTrYc8xt2GURXrQpf9kt1A',
    appId: '1:929386302424:ios:e7aaf004dcce6d5dfb00ad',
    messagingSenderId: '929386302424',
    projectId: 'challenge-app-d20ba',
    storageBucket: 'challenge-app-d20ba.firebasestorage.app',
    iosBundleId: 'com.example.challengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlEk21zTh9HTrYc8xt2GURXrQpf9kt1A',
    appId: '1:929386302424:ios:e7aaf004dcce6d5dfb00ad',
    messagingSenderId: '929386302424',
    projectId: 'challenge-app-d20ba',
    storageBucket: 'challenge-app-d20ba.firebasestorage.app',
    iosBundleId: 'com.example.challengeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWhO7-Nz65Cx7NFt-tleuqrCvj7g4PpOQ',
    appId: '1:929386302424:web:ff5403b0c6f95013fb00ad',
    messagingSenderId: '929386302424',
    projectId: 'challenge-app-d20ba',
    authDomain: 'challenge-app-d20ba.firebaseapp.com',
    storageBucket: 'challenge-app-d20ba.firebasestorage.app',
    measurementId: 'G-Q2S0P95919',
  );
}
